
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTczMjY5MjM5MSwiZXhwIjoxNzMzOTg4MzkxfQ.8gHubHQ61Df3kYbKkUPr5qGCzNhz9siztmvB2i08L4o

### user ========================================================
### get
GET http://localhost:8080/api/v1/user/3
Authorization: Bearer {{token}}

### gets
GET http://localhost:8080/api/v1/users
Authorization: Bearer {{token}}

###
POST http://localhost:8080/api/v1/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "user acc",
    "userName": "userAcc",
    "email": "userAcc@gmail.com",
    "pass": "12345",
    "gender": null,
    "admin": true 
}
### edit
PUT  http://localhost:8080/api/v1/user/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Lê Trung Hậu",
    "userName": "leetrunghaau1",
    "email": "leetrunghaaus@gmail.com",
    "gender": null,
    "admin": true 
}
### reset pass cho user
PUT  http://localhost:8080/api/v1/user/reset-pass/7
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "pass": "12345"
}

### delete
DELETE http://localhost:8080/api/v1/user/5
Authorization: Bearer {{token}}
