@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTczMzM0NjAwOCwiZXhwIjoxNzM0NjQyMDA4fQ.vH9J-rKojkQ7yZjFMV_W10AJg9TSNMODFLfuii4cChc

### gets id
GET   http://localhost:8080/api/v1/project/4/issues/1
Authorization: Bearer {{token}}
### gets by project id
GET   http://localhost:8080/api/v1/issuess?project=4
Authorization: Bearer {{token}}
### gets by project id
GET   http://localhost:8080/api/v1/issuess?owner=4
Authorization: Bearer {{token}}

### create
POST http://localhost:8080/api/v1/project/4/issues
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "công việc 2",
    "statusId": null,
    "trackerId": null,
    "priorityId": null,
    "assignee": null,
    "start": null,
    "end": null,
    "updated": null,
    "parentId": null
}

### update
PUT http://localhost:8080/api/v1/project/4/issues/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "công việc 2",
    "statusId": 26,
    "trackerId": 26,
    "priorityId": 26,
    "assignee": 7,
    "start": null,
    "end": null,
    "updated": null,
    "parentId": 1
}
### update
PUT http://localhost:8080/api/v1/project/4/issues/1/content
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "công việc 2",
    "trackerId": 10,
    "priorityId": 10,
    "parentId": 2
}
### update
PUT http://localhost:8080/api/v1/project/4/issues/1/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "statusId": 10
}
### update
PUT http://localhost:8080/api/v1/project/4/issues/1/assignee
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId":2
}
###
PUT http://localhost:8080/api/v1/project/4/issues/1/due
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "start":"2024-11-27",
    "end":"2024-11-29"
}

### delete 
DELETE  http://localhost:8080/api/v1/project/4/issues/2
Authorization: Bearer {{token}}

####
