# @import ./var.http
####
POST http://{{server}}:{{port}}/api/v1/project/4/issues/3/note
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content":"abc"
}
####
POST http://{{server}}:{{port}}/api/v1/project/4/issues/3/notes
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {
        "content":"hôm nay làm gì"
    },
    {
        "content":"nagyf mai làm gì"
    },
    {
        "content":"ngày mốt làm gì"
    }
]
###
PUT  http://{{server}}:{{port}}/api/v1/project/4/issues/3/note/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content":"abc"
}
###
DELETE   http://{{server}}:{{port}}/api/v1/project/4/issues/3/note/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content":"abc"
}
###################################
POST http://{{server}}:{{port}}/api/v1/project/4/issues/3/check-list
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"abc",
    "checked":true
}
####
POST http://{{server}}:{{port}}/api/v1/project/4/issues/3/check-lists
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {
        "name":"hôm nay làm gì"
    },
    {
        "name":"nagyf mai làm gì"
    },
    {
        "name":"ngày mốt làm gì"
    }
]
###
PUT  http://{{server}}:{{port}}/api/v1/project/4/issues/3/check-list/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"ok",
    "checked":true
}
###
DELETE   http://{{server}}:{{port}}/api/v1/project/4/issues/3/check-list/5
Authorization: Bearer {{token}}
###
GET  http://{{server}}:{{port}}/api/v1/project/11/issues/20/comments
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://{{server}}:{{port}}/api/v1/project/4/issues/3/comment
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "value":"dễ",
    "parentId":6
}
###
PUT  http://{{server}}:{{port}}/api/v1/project/4/issues/3/comment/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "value":"ok"
}
###
DELETE   http://{{server}}:{{port}}/api/v1/project/4/issues/3/comment/5
Authorization: Bearer {{token}}
