# @import ./var.http
### quản lý các role của 1 dự án
GET   http://{{server}}:{{port}}/api/v1/project/4/roles
Authorization: Bearer {{token}}

### create
POST   http://{{server}}:{{port}}/api/v1/project/9/role
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
### edit
PUT   http://{{server}}:{{port}}/api/v1/project/9/role/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test edit"
}

### delete 
DELETE  http://{{server}}:{{port}}/api/v1/project/9/role/12
Authorization: Bearer {{token}}

##################################################################################
###  thiết kết quyền role

GET  http://{{server}}:{{port}}/api/v1/permissions
## get by role
GET  http://{{server}}:{{port}}/api/v1/project/9/role/1d1/permissions
Authorization: Bearer {{token}}

## get by project
GET  http://{{server}}:{{port}}/api/v1/project/11/permissions
Authorization: Bearer {{token}}

###  cấp quyền 
POST http://{{server}}:{{port}}/api/v1/project/9/role/1d1/permission
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "permissionId": 1
}
### bỏ quyền 
DELETE  http://{{server}}:{{port}}/api/v1/project/9/role/12/permission/7
Authorization: Bearer {{token}}

##################################################################################
### quản lý các thành viên của 1 dự án  

GET http://{{server}}:{{port}}/api/v1/project/15/members
Authorization: Bearer {{token}}

### add member 
POST  http://{{server}}:{{port}}/api/v1/project/4/member
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "userId": 2
}

### delete member 
DELETE   http://{{server}}:{{port}}/api/v1/project/9/member/11
Authorization: Bearer {{token}}

##################################################################################
###  cấp quyền cho member của dự án
POST http://{{server}}:{{port}}/api/v1/project/9/member/12/role
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "roleId": 92
}
### bỏ quyền cho user
DELETE  http://{{server}}:{{port}}/api/v1/project/9/member/6/role/5
Authorization: Bearer {{token}}



