@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTczMjY5MjM5MSwiZXhwIjoxNzMzOTg4MzkxfQ.8gHubHQ61Df3kYbKkUPr5qGCzNhz9siztmvB2i08L4o
@projectID=1
### project
GET http://localhost:8080/api/v1/project/1
Authorization: Bearer {{token}}

### gets
GET http://localhost:8080/api/v1/projects
Authorization: Bearer {{token}}

### create
POST http://localhost:8080/api/v1/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "dự án 5",
    "description": "mô tat dự án 1",
    "parentId": null,
    "public": 1,
    "active": 1
}

### update
PUT http://localhost:8080/api/v1/project/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "dự án 9",
    "description": "mô tat dự án 1",
    "parentId": null,
    "public": 1,
    "active": 0
}
### delete
DELETE http://localhost:8080/api/v1/project/5
Authorization: Bearer {{token}}

### tracker =======================================================================================================
GET   http://localhost:8080/api/v1/project/{{projectID}}/trackers
Authorization: Bearer {{token}}

### create
POST   http://localhost:8080/api/v1/project/9/tracker
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
### edit
PUT   http://localhost:8080/api/v1/project/9/tracker/31
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test edit"
}

### delete 
DELETE  http://localhost:8080/api/v1/project/9/tracker/31
Authorization: Bearer {{token}}

### Priority =======================================================================================================
GET   http://localhost:8080/api/v1/project/9/priorities 
Authorization: Bearer {{token}}

### create
POST   http://localhost:8080/api/v1/project/9/priority
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
### edit
PUT   http://localhost:8080/api/v1/project/9/priority/31
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test edit"
}

### delete 
DELETE  http://localhost:8080/api/v1/project/9/priority/31
Authorization: Bearer {{token}}

### status =======================================================================================================
GET   http://localhost:8080/api/v1/project/9/statuses
Authorization: Bearer {{token}}

### create
POST   http://localhost:8080/api/v1/project/9/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test"
}
### edit
PUT   http://localhost:8080/api/v1/project/9/status/31
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "test edit"
}

### delete 
DELETE  http://localhost:8080/api/v1/project/9/status/31
Authorization: Bearer {{token}}
