# @import ./var.http
### đăng ký
POST http://{{server}}:{{port}}/api/v1/sign/up
Content-Type: application/json

{
    "name": "acc for user2",
    "userName": "user2Acc",
    "email": "user2Acc@gmail.com",
    "pass":"123456"
}
### đăng nhập
POST http://{{server}}:{{port}}/api/v1/sign/in
Content-Type: application/json

{
    "user":"leetrunghaau",
    "pass":"123456789"
}

### info ========================================================== 
GET http://{{server}}:{{port}}/api/v1/info
Authorization: Bearer {{token}}

### update info
PUT  http://{{server}}:{{port}}/api/v1/info
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acc for user",
    "userName": "userAcc",
    "email": "userAcc@gmail.com",
    "gender": "nam"
}
### change pass
PUT  http://{{server}}:{{port}}/api/v1/info/change-pass
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "oldPass":"1234567",
    "newPass":"123456"
}

