@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTczMjY5MjM5MSwiZXhwIjoxNzMzOTg4MzkxfQ.8gHubHQ61Df3kYbKkUPr5qGCzNhz9siztmvB2i08L4o
### đăng ký
POST http://localhost:8080/api/v1/sign/up
Content-Type: application/json

{
    "name": "acc for user2",
    "userName": "user2Acc",
    "email": "user2Acc@gmail.com",
    "pass":"123456"
}
### đăng nhập
POST http://localhost:8080/api/v1/sign/in
Content-Type: application/json

{
    "user":"leetrunghaau1",
    "pass":"123456"
}

### info ========================================================== 
GET http://localhost:8080/api/v1/info
Authorization: Bearer {{token}}

### update info
PUT  http://localhost:8080/api/v1/info
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "acc for user",
    "userName": "userAcc",
    "email": "userAcc@gmail.com",
    "gender": "nam"
}
### change pass
PUT  http://localhost:8080/api/v1/info/change-pass
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "oldPass":"1234567",
    "newPass":"123456"
}

